project_name: prm

builds:
  - binary: prm
    ldflags:
      - -s -w -X github.com/ldez/prm/meta.version={{.Version}} -X github.com/ldez/prm/meta.commit={{.Commit}} -X github.com/ldez/prm/meta.date={{.Date}}

    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm

archive:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE

snapcraft:
  publish: true
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  summary: Pull Request Manager for Maintainers
  description: |
    PRM Pull Request Manager for Maintainers.
  grade: devel
  #grade: stable
  confinement: classic

release:
  disable: true

