language: go

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $GOPATH/pkg/mod

matrix:
  fast_finish: true
  include:
    - go: 1.12.x
      env: STABLE=true
    - go: 1.x
    - go: tip
  allow_failures:
    - go: tip

env:
  global:
    - GO111MODULE=on

before_install:
  # Install linters and misspell
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.17.1
  - golangci-lint --version

  # Hugo - documentation
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

install:
  - go mod download

after_success:
  - make docs-build

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $STABLE = true
  - deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/public
    verbose: true
    on:
      condition: $STABLE = true
