language: go

go:
  - 1.12.x
  - 1.x

sudo: false

env:
  - GO111MODULE=on

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  # Install linters and misspell
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.17.1
  - golangci-lint --version

  # Hugo - documentation
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

install:
  - echo "TRAVIS_GO_VERSION=$TRAVIS_GO_VERSION"
  - make dependencies

after_success:
  - make docs-build

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.x$
  - deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/public
    verbose: true
    on:
      condition: $TRAVIS_GO_VERSION =~ ^1\.x$
