
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/containous/flaeg"
  version = "^1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/ldez/go-git-cmd-wrapper"
  version = "^0.20.0"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.4.1"

[[override]]
  branch = "master"
  name = "github.com/ogier/pflag"

[[override]]
  branch = "master"
  name = "github.com/davecgh/go-spew"

[[override]]
  branch = "master"
  name = "google.golang.org/appengine"

